# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Mon Nov  7 15:39:04 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("PySide a simple Game")
        MainWindow.resize(800, 230)
        self.widget = QtGui.QWidget(MainWindow)
        self.widget.setEnabled(True)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vertical = QtGui.QVBoxLayout()
        self.vertical.setObjectName("vertical")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.offen = QtGui.QLabel(self.widget)
        self.offen.setObjectName("offen")
        self.gridLayout.addWidget(self.offen, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.falsch = QtGui.QLabel(self.widget)
        self.falsch.setObjectName("falsch")
        self.gridLayout.addWidget(self.falsch, 2, 1, 1, 1)
        self.gesamt = QtGui.QLabel(self.widget)
        self.gesamt.setObjectName("gesamt")
        self.gridLayout.addWidget(self.gesamt, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.korrekt = QtGui.QLabel(self.widget)
        self.korrekt.setObjectName("korrekt")
        self.gridLayout.addWidget(self.korrekt, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.spiele = QtGui.QLabel(self.widget)
        self.spiele.setObjectName("spiele")
        self.gridLayout.addWidget(self.spiele, 4, 1, 1, 1)
        self.vertical.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.vertical, 0, 0, 1, 1)
        self.vertical_2 = QtGui.QVBoxLayout()
        self.vertical_2.setObjectName("vertical_2")
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_11.setObjectName("label_11")
        self.vertical_2.addWidget(self.label_11)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton7 = QtGui.QPushButton(self.widget)
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout_3.addWidget(self.pushButton7, 1, 2, 1, 1)
        self.pushButton9 = QtGui.QPushButton(self.widget)
        self.pushButton9.setObjectName("pushButton9")
        self.gridLayout_3.addWidget(self.pushButton9, 1, 4, 1, 1)
        self.pushButton8 = QtGui.QPushButton(self.widget)
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout_3.addWidget(self.pushButton8, 1, 3, 1, 1)
        self.pushButton11 = QtGui.QPushButton(self.widget)
        self.pushButton11.setObjectName("pushButton11")
        self.gridLayout_3.addWidget(self.pushButton11, 2, 1, 1, 1)
        self.pushButton10 = QtGui.QPushButton(self.widget)
        self.pushButton10.setObjectName("pushButton10")
        self.gridLayout_3.addWidget(self.pushButton10, 2, 0, 1, 1)
        self.pushButton13 = QtGui.QPushButton(self.widget)
        self.pushButton13.setObjectName("pushButton13")
        self.gridLayout_3.addWidget(self.pushButton13, 2, 3, 1, 1)
        self.pushButton12 = QtGui.QPushButton(self.widget)
        self.pushButton12.setObjectName("pushButton12")
        self.gridLayout_3.addWidget(self.pushButton12, 2, 2, 1, 1)
        self.pushButton1 = QtGui.QPushButton(self.widget)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout_3.addWidget(self.pushButton1, 0, 1, 1, 1)
        self.pushButton2 = QtGui.QPushButton(self.widget)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout_3.addWidget(self.pushButton2, 0, 2, 1, 1)
        self.pushButton4 = QtGui.QPushButton(self.widget)
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout_3.addWidget(self.pushButton4, 0, 4, 1, 1)
        self.pushButton3 = QtGui.QPushButton(self.widget)
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout_3.addWidget(self.pushButton3, 0, 3, 1, 1)
        self.pushButton5 = QtGui.QPushButton(self.widget)
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout_3.addWidget(self.pushButton5, 1, 0, 1, 1)
        self.pushButton6 = QtGui.QPushButton(self.widget)
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout_3.addWidget(self.pushButton6, 1, 1, 1, 1)
        self.pushButton0 = QtGui.QPushButton(self.widget)
        self.pushButton0.setObjectName("pushButton0")
        self.gridLayout_3.addWidget(self.pushButton0, 0, 0, 1, 1)
        self.pushButton14 = QtGui.QPushButton(self.widget)
        self.pushButton14.setObjectName("pushButton14")
        self.gridLayout_3.addWidget(self.pushButton14, 2, 4, 1, 1)
        self.vertical_2.addLayout(self.gridLayout_3)
        self.horizontal = QtGui.QHBoxLayout()
        self.horizontal.setObjectName("horizontal")
        self.neu = QtGui.QPushButton(self.widget)
        self.neu.setMinimumSize(QtCore.QSize(60, 0))
        self.neu.setMaximumSize(QtCore.QSize(100, 30))
        self.neu.setObjectName("neu")
        self.horizontal.addWidget(self.neu)
        self.ende = QtGui.QPushButton(self.widget)
        self.ende.setMaximumSize(QtCore.QSize(100, 30))
        self.ende.setObjectName("ende")
        self.horizontal.addWidget(self.ende)
        self.vertical_2.addLayout(self.horizontal)
        self.gridLayout_2.addLayout(self.vertical_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.widget)
        self.status = QtGui.QStatusBar(MainWindow)
        self.status.setObjectName("status")
        MainWindow.setStatusBar(self.status)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ende, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("PySide a simple Game", "PySide a simple Game", None, QtGui.QApplication.UnicodeUTF8))
        self.offen.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">offen:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.falsch.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.gesamt.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">gesamt</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.korrekt.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">korrekt:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">falsch:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Spiele:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.spiele.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Drücken Sie die Buttons in aufsteigender Richtung!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton7.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton9.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton8.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton11.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton10.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton13.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton12.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton1.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton2.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton4.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton3.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton5.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton6.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton0.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton14.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.neu.setText(QtGui.QApplication.translate("MainWindow", "Neu", None, QtGui.QApplication.UnicodeUTF8))
        self.ende.setText(QtGui.QApplication.translate("MainWindow", "Ende", None, QtGui.QApplication.UnicodeUTF8))

